modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="${issues_url}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_url}"
	iconFile="assets/trailiertales/icon.png"
	authors="Lunade/AViewFromTheTop, wigglewoggle"
	description='''
Overhauls the Trails & Tales update, adding features and improving existing ones.
    '''

[[mixins]]
config="trailiertales.mixins.json"

[[ dependencies.trailiertales ]]
	modId="neoforge"
	type="required"
	versionRange="[${minecraft_version},)"
	ordering="NONE"
	side="BOTH"

[[ dependencies.trailiertales ]]
	modId="minecraft"
	type="required"
	versionRange="[${minecraft_version},)"
	ordering="NONE"
	side="BOTH"

[[ dependencies.trailiertales ]]
	modId="frozenlib"
	type="required"
	versionRange="[${frozenlib_version},)"
	ordering="NONE"
	side="BOTH"

[[ dependencies.trailiertales ]]
	modId="cloth-config"
	type="optional"
	versionRange="*"
	ordering="NONE"
	side="BOTH"

["lithium:options"]
"mixin.world.raycast" = false
